### ISSUE TITLE
Feature Request to Change to requested Pages # from API 

### ISSUE THREAD

**Issue by lebluxtv** [elgatosf/streamdeck-javascript-sdk#11]
It would be really usefull to be able to change the current page of the current profile so we can get specific buttons we need depending events of the stream ( that would be handled with streamer.bot ) 

Please !!!

**Comment by GeekyEggo** [comment]
Hey @lebluxtv, as part of version 6.5 (pending release) we've added the ability to specify a page when invoking the `switchToProfile` event; this will enable switching to a specific page within a profile.

**Comment by GeekyEggo** [comment]
With the release of Stream Deck 6.5, switching profiles now supports specifying the page number as an optional parameter. You can [read more about this change on our documentation page](https://docs.elgato.com/sdk/plugins/events-sent#switchtoprofile).
