### ISSUE TITLE
$SD.setFeedback not updating SD+ layout values

### ISSUE THREAD

**Issue by kevin-wynn** [elgatosf/streamdeck-javascript-sdk#2]
Hello, I am working on a plugin that will let me cycle through various text options using the knob to select different defined text values from the property inspector. Then upon pressing the knob it will fire an event based on the value selected.

I am having trouble getting a layout to update using the `setFeedback()` function provided from the sdk. This is the layout my plugin is using via a layouts.json file

```json
{
  "id": "com.robohouse.devdeck.dial",
  "items": [
    {
      "key": "title",
      "type": "text",
      "rect": [16, 10, 136, 24],
      "font": { "size": 16, "weight": 600 },
      "alignment": "left"
    },
    {
      "key": "value",
      "type": "text",
      "rect": [76, 40, 108, 32],
      "font": { "size": 12, "weight": 600 },
      "alignment": "right"
    }
  ]
}
```

And my manifest.json

```json
{
  "SDKVersion": 2,
  "Author": "Kevin Wynn",
  "CodePath": "app.html",
  "Description": "Developer toolbelt.",
  "Name": "Dev Deck",
  "Icon": "template/assets/actionimage",
  "URL": "https://github.com/kevin-wynn/devdeck",
  "Version": "1.0.0",
  "Software": {
    "MinimumVersion": "5.0"
  },
  "OS": [
    {
      "Platform": "mac",
      "MinimumVersion": "10.11"
    },
    {
      "Platform": "windows",
      "MinimumVersion": "10"
    }
  ],
  "Category": "Developer Toolkit",
  "CategoryIcon": "template/assets/actionimage",
  "Actions": [
    {
      "Icon": "template/assets/actionimage",
      "Name": "K8s Terminal",
      "Controllers": ["Encoder"],
      "Encoder": {
        "layout": "layous/layouts.json",
        "TriggerDescription": {
          "Rotate": "Change K8s Clusters",
          "Push": "Select and launch terminal for K8s Cluster"
        }
      },
      "States": [
        {
          "Image": "template/assets/actionimage"
        }
      ],
      "Tooltip": "This is an example tooltip",
      "UUID": "com.robohouse.devdeck.dial",
      "PropertyInspectorPath": "template/property-inspector/inspector.html"
    }
  ]
}
```

And this is what my app.js looks like where I reference the sdk, connect, and register events for the various actions. Console logs fire fine when debugging using the devtools, however nothing updates on my Stream Deck + itself...

```javascript
/// <reference path="libs/js/action.js" />
/// <reference path="libs/js/stream-deck.js" />
/// <reference path="libs/js/utils.js" />

const dialAction = new Action("com.robohouse.devdeck.dial");

$SD.onConnected(
  ({ actionInfo, appInfo, connection, messageType, port, uuid }) => {
    console.log("Stream Deck connected!");
  }
);

dialAction.on;

dialAction.onWillAppear(({ context, payload }) => {
  $SD.setFeedback(context, {
    title: "this is a title",
    value: "this is my value",
  });
});

dialAction.onDialRotate(({ action, context, device, event, payload }) => {
  if (payload.hasOwnProperty("ticks")) {
    $SD.setFeedback(context, {
      title: `Knob turning: ${payload.ticks === -1 ? "left" : "right"}`,
    });
  }
});

dialAction.onDialPress(({ action, context, device, payload }) => {
  // only fire the event on the press, nothing to do on the release
  if (payload.pressed) {
    console.log("Dial press");
    console.log("action:", action);
    console.log("context:", context);
    console.log("device:", device);
    console.log("payload:", payload);
  }
});
```

I have noticed that if I set a title, and then remove it, it will update to the title I have defined in the `onDialRotate` listener. But never updates on actions from the actual stream deck.

Am I missing something somewhere?

Thanks in advance!

**Comment by ChekTek** [comment]
Hi!

I tried out your code, and things seem to be working as expected for me: https://share.cleanshot.com/CMPcDSxq 

It's worth noting that the "title" key is shared with the property inspector's built-in title input. So if you type something into the property inspector title input, it will take priority over the `setFeedback` call. You may want to try setting the `UserTitleEnabled` property to false in the manifest.json (https://developer.elgato.com/documentation/stream-deck/sdk/manifest/#actions). That will disable the title field in the property inspector and prevent it from overriding your layout title. You could also try changing the key to something other than "title" and see if that helps.

**Comment by kevin-wynn** [comment]
I removed my custom property-inspector and things started working as expected. The problem must lie somewhere there, thank you for the insight!
