### ISSUE TITLE
Errors in API documentation

### ISSUE THREAD

**Issue by bjanders** [elgatosf/streamdeck-javascript-sdk#6]
This is not the correct project to report in, but I don't know in which one I should report API documentation errors.

On https://developer.elgato.com/documentation/stream-deck/sdk/registration-procedure/ there's the example (it two places):
```
websocket.onopen = function()
{
  // WebSocket is connected, register the plugin
  {
    "event": inRegisterEvent,
    "uuid": inPluginUUID
  }

  websocket.send(JSON.stringify(json));
}
```

This is missing `var json =`, i.e., it should be:
```
websocket.onopen = function()
{
  // WebSocket is connected, register the plugin
  var json = {
    "event": inRegisterEvent,
    "uuid": inPluginUUID
  }

  websocket.send(JSON.stringify(json));
}
```

**Comment by ninjadev64** [comment]
This has since been fixed, you may want to close the issue
