### ISSUE TITLE
Allow openUrl method to interface with URI's

### ISSUE THREAD

**Issue by Fevol** [elgatosf/streamdeck-javascript-sdk#7]
**What is the problem and what would need to be changed?** 
Currently, the `$SD.openUrl` method seems to only be able to open HTTP links in the browser. 
It would however be nice to have the option to execute URI actions (with `openUrl`, or a new function that would be better suited for this task). That way, we could easily interface with programs that expose URI interfaces, and don't have to restort to implementing an entire websocket connection and backend handler to communicate with these applications.

**Example snippet:**
```ts
const myAction = new Action('com.elgato.template.action');

myAction.onKeyUp(({ action, context, device, event, payload }) => {
       // WORKS - Open Stream Deck web page in user's browser 
	$SD.openUrl('https://www.elgato.com/streamdeck')

       // DOES NOT WORK - Open Windows Calculator application
       $SD.openUrl('calculator://')

       // DOES NOT WORK - Open system explorer in specified folder
       $SD.openUrl('file:///C:/Users/Fevol/Documents/')

       // DOES NOT WORK - Start playing a song on Spotify by specified track ID
       $SD.openUrl('spotify://track:4cOdK2wGLETKBW3PvgPWqT')
});
```
_(URI functionality can be tested out by entering them in browser search bar or pasting them into Win+R)_

<br>

**Other related code and documentation:**

[Documentation](https://developer.elgato.com/documentation/stream-deck/sdk/events-sent/#openurl)

https://github.com/elgatosf/streamdeck-javascript-sdk/blob/53d120c6d41104e9cae180d0cc30fe25b357f46b/js/api.js#L293-L303

<br>
<br>

Many thanks in advance for your consideration!

**Comment by ninjadev64** [comment]
This may be more of a Stream Deck SDK/software limitation than of the JavaScript library, I think.

**Comment by Fevol** [comment]
> This may be more of a Stream Deck SDK/software limitation than of the JavaScript library, I think.

Actually, I do think the Stream Deck SDK itself supports opening URI links, you can test this yourself by creating a shortcut `System > Website` directly inside the Stream Deck app, and adding one of the above links to it (e.g.: `file://`). I imagine that somewhere in the communication between the JS SDK and the dekstop application/server, there is a check to see whether the link is prefixed with `https://`, but that's just a guess on my part.

**Comment by ninjadev64** [comment]
Oh ok, I've never actually used the Stream Deck software, so I didn't know. (I use my own hardware with my own software that implements the SDK).

**Comment by ChekTek** [comment]
Hi @Fevol! 

This is a limitation on the Stream Deck application side, but a good feature request! I'm reporting this to the Stream Deck core team, but since this doesn't really apply to the JavaScript SDK, I will close this ticket for now.

**Comment by Fevol** [comment]
Thanks for the response, I appreciate it!

Will the news of the implementation of the feature be posted on the official [release notes](https://help.elgato.com/hc/en-us/sections/5162671529357-Elgato-Stream-Deck-Software-Release-Notes) page, or is there someplace else I should look?

**Comment by ChekTek** [comment]
> 

You can check back in GitHub discussions for an announcement. You can also join our [Maker Discord](https://discord.gg/VeprQMEWeB). It will also be available on the [SDK changelog](https://docs.elgato.com/sdk/plugins/changelog).

We are working on a SDK newsletter to try and bring one source of truth for updates as well, so stay tuned for that!
