### ISSUE TITLE
Allow Next/Previous Page actions in SDK

### ISSUE THREAD

**Issue by planetshg** [elgatosf/streamdeck-javascript-sdk#9]
Currently, the SDK has no action for switching to the next/previous SD page.

Can we allow our custom actions perform the next page and previous page action/call? Let's say, using JavaScript I would like trigger the same behavior as the "Next Page" and "Previous Page" actions from Elgato's "Navigation" category do.

**Comment by ChekTek** [comment]
Hi @planetshg 

Typically, we recommend plugins use built in profiles rather than pages, do you have a specific use case for pages?

**Comment by planetshg** [comment]
Hi @ChekTek,

sure:
As a Stream Deck **+** user in a day-to-day multi-tasking scenario, I want to monitor and control various applications at once, also some system-level settings. Often I will not have the application in focus that is going to receive an SD+ command next, or in case of system-level settings there is no explicit process to hook for switching profiles.

Also, I need to make efficient use of the SD's only eight buttons. → I need to be cherry-picking and condensing desired functions from various plugins into a few SD pages.

Finally, rather than assigning "Next Page" to a button, going from this request I would like to publish a plugin that enables "Next Page" and "Previous Page" actions by turning SD+ dials, increasing overall flexibility and speed.

**Comment by GeekyEggo** [comment]
Hey @planetshg, are you familiar with the swipe gestures on the Stream Deck+ touchpad? Swiping left and right allows you to navigate to the previous and next pages respectively, and frees up the need for two page-navigation actions.

**Comment by planetshg** [comment]
Thank you @GeekyEggo, yes I'm familiar with the gesture. However I find it not much appealing ergonomically (needs a totally different haptic "approach"), and using multiple swipes for consecutive page switching is also not comparable to quickly turning a dial. I'm convinced making use of the SD+ dials' precise clicks and speed of a dial is a good improvement.

**Comment by GeekyEggo** [comment]
Thanks for expanding on your feedback, it's helped us better understand what's being asked.

Having spoken with the Stream Deck team, they've confirmed this is something they've previously discussed, and whilst it isn't on the roadmap at this stage, knowing there are users that are interested in such functionality helps us when prioritising potential future functionality. Your feedback is appreciated. 🙌

With this now on the Stream Deck teams radar, I'm going to close this ticket. Thanks again.
